//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoslynAnalyzerExamples {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoslynAnalyzerExamples.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex patterns should be syntactically valid..
        /// </summary>
        internal static string AnalyzerDescription1 {
            get {
                return ResourceManager.GetString("AnalyzerDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex error {0}.
        /// </summary>
        internal static string AnalyzerMessageFormat1 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex error parsing string argument.
        /// </summary>
        internal static string AnalyzerTitle1 {
            get {
                return ResourceManager.GetString("AnalyzerTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potential Open Redirects..
        /// </summary>
        internal static string RedirectAnalyzerDesc {
            get {
                return ResourceManager.GetString("RedirectAnalyzerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for potential Open Redirects..
        /// </summary>
        internal static string RedirectAnalyzerDesc2 {
            get {
                return ResourceManager.GetString("RedirectAnalyzerDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        internal static string RedirectCategory {
            get {
                return ResourceManager.GetString("RedirectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        internal static string RedirectCategory2 {
            get {
                return ResourceManager.GetString("RedirectCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Info {0}.
        /// </summary>
        internal static string RedirectMessageFormat {
            get {
                return ResourceManager.GetString("RedirectMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Redirect Validation.
        /// </summary>
        internal static string RedirectTitle {
            get {
                return ResourceManager.GetString("RedirectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Redirect Validation.
        /// </summary>
        internal static string RedirectTitle2 {
            get {
                return ResourceManager.GetString("RedirectTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzes for Response.Write For XSSFlaw.
        /// </summary>
        internal static string ResponseAnalyzerDesc {
            get {
                return ResourceManager.GetString("ResponseAnalyzerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.Write Info {0}.
        /// </summary>
        internal static string ResponseMessageFormat {
            get {
                return ResourceManager.GetString("ResponseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.Write Analyzer for XSS.
        /// </summary>
        internal static string ResponseTitle {
            get {
                return ResourceManager.GetString("ResponseTitle", resourceCulture);
            }
        }
    }
}
